---
notifications:
  email:
    on_success: never
    on_failure: change

language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy'

install:
  - pip install coveralls
  - python setup.py install

script:
  - python setup.py test

after_script:
  - coveralls
